name: Secrets

on:
  workflow_dispatch:

jobs:
  testing_secrets:
    name: Test secrets
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: primer secreto
        run: echo ${{ secret.MY_SECRET }}
